# Generated by Django 3.1.5 on 2021-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_db_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
